settings:
  application:
    mode: dev  # dev开发环境 test测试环境 prod线上环境
    host: 0.0.0.0
    name: testApp
    port: 8000
    readtimeout: 1
    writertimeout: 2
    domain: localhost:8000
    ishttps: false
  ssl:
    key: keystring
    pem: temp/pem.pem
  log:
    operdb: false
    dir: temp/logs
  jwt:
    secret: go-admin
    timeout: 3600
  database:
    dbtype: mysql
    sqlite:
      masterconn: ./sqlite3.db
    mysql:
      masterconn: user:password@/tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local
    pgsql:
      masterconn: host=myhost port=myport user=gorm dbname=gorm password=mypassword
