name: Go Continuous Integration
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
        GOPATH: ${{ github.workspace }}/go
    strategy:
      matrix:
        go: [1.13]
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into GOPATH
      uses: actions/checkout@v2
      with:
        path: go/src/firebase.google.com/go
    
    - name: Get dependencies
      run: cd ${{ github.workspace }}/src/go-admin
           go build

